title = "Toma Nistor"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "web developer", "ruby on rails", "javascript", "postgres", "San Diego"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-70206008-1"

[Params]
    tagline = "Toma Nistor"
    author = "Toma Nistor"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA. I enjoy using multiple tools to engineer and build powerful websites and apps."
    logoBig = "/images/logo/Toma-Nistor-Logo-450px.png"
    logoSmall = "/images/logo/Toma-Nistor-Logo-150px.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo/Toma-Nistor-Logo-Banner-Dark.png"
    twitter = "TomaNistor"
    linkedin = "tomanistor"
    github = "tomanistor"
    email = "toma@tomanistor.com"
    googleTagManager = "GTM-T94X59P"
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = true
    cacheBustJS = true
    ajaxFormspree = true

[taxonomies] # Leave this here to remove the default "tag" and "category" taxonomies

[permalinks]
    gallery = "/"

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
